language: node_js
node_js:
  - '8'
cache:
  directories:
    - node_modules  
install:
  - npm install
  - npm install -g codecov
script:
  - npm run build-css
  - npm run build
  - npm test -- --coverage  --runInBand --no-cache --mapCoverage
after_success:
  - codecov -t 8a045ae0-f9d2-4bf2-8b21-b6c1da2a161c
